---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: heading
  label: Homepage
- type: document
  path: exampleSite/content/english/_index.md
  label: Homepage
- type: heading
  label: Blog
- type: document
  path: exampleSite/content/english/blog/_index.md
  label: 'Blog '
- type: directory
  path: exampleSite/content/english/blog
  label: Blog Posts
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - blog-post
- type: document
  path: exampleSite/content/english/services.md
  label: Services
- type: document
  path: exampleSite/content/english/contact.md
  label: Contact
- type: document
  path: exampleSite/content/english/team.md
  label: Team
- type: heading
  label: Others Page
- type: document
  path: exampleSite/content/english/about.md
  label: About
- type: document
  path: exampleSite/content/english/mind-map.md
  label: Mind Map
- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content/english
  label: All Pages
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - new-page
- type: heading
  label: Configuration
- type: document
  path: exampleSite/config/_default/config.toml
  label: Configuration
- type: document
  path: exampleSite/config/_default/params.toml
  label: Parameters
- type: document
  path: config.toml
  label: Variables & Plugins
- type: document
  path: exampleSite/config/_default/languages.toml
  label: Languages
- type: document
  path: exampleSite/config/_default/menus.en.toml
  label: Menu
- type: directory
  path: exampleSite/i18n
  label: i18n Translations
  create: all
  match: "**/*"
upload_dir: exampleSite/assets/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:node16
  mount_path: "/srv"
  working_dir: "/srv/exampleSite"
  install_dependencies_command: hugo --minify --gc --themesDir ../..
  instant_preview_command: npx http-server
version: 0.81.0
